### ISSUE TITLE
오류 보고

### ISSUE THREAD

**Issue by joelkim** [hyunwoongko/kss#1]
안녕하세요, 다음과 같은 텍스트를 넣으면 제대로 분리가 되지 않습니다.

텍스트:
```
당사의 정관에 의한 발행할 주식의 총수는 500,000,000주(1주의 금액:5,000원)이며 2017년말 현재 당사가 발행한 기명식 보통주식(이하 보통주) 및 무의결권기명식 우선주식(이하 우선주)의 수는 각각 129,098,494주와 18,250,580주입니다(소각주식수 제외). 당사는 2017년말 현재까지 보통주 26,510,843주와 우선주 5,642,847주를 이사회결의에 의거 이익으로 소각한 바 있습니다.
```

분리 결과:
```
( '당사의 정관에 의한 발행할 주식의 총수는 500,000,000주(1주의 금액:5,000원)이며 2017년말 현재 당사가 발행한 기명식 보통주식(이하 보통주) 및 무의결권기명식 우선주식(이하 우선주)의 수는 각각 129,098,494주와 18,250,580주입니다',
 '(소각주식수 제외). 당사는 2017년말 현재까지 보통주 26,510,843주와 우선주 5,642,847주를 이사회결의에 의거 이익으로 소각한 바 있습니다.')
```

**Comment by hyunwoongko** [comment]
지금 보기에는 나쁘지 않은 결과 같은데 혹시 어떻게 분리되기를 원하시는건가요?

**Comment by joelkim** [comment]
```
(소각주식수 제외).
```
마침표가 괄호 부분 뒤에 있기 때문에 이 괄호는 앞 문장에 붙어서 다음과 같이 되어야 합니다.

```
['당사의 ... (중간 생략)... 18,250,580주입니다(소각주식수 제외).',
'당사는 ... (이하 생략)']
```

**Comment by hyunwoongko** [comment]
- 네. 제 생각에도 말씀하신대로 분절하는 것이 더 타당하다고 보여집니다.

- 그러나 현재 만들어진 알고리즘에 큰 변화를 주지 않는 이상 위와 같은 경우까지 고려하며 분절하기는 어렵습니다. (저걸 분절하는게 불가능 하다는게 아니라, 현재 구현이나 컨셉에서 뭔가의 장치를 추가하지 않는 이상 안된다는 것입니다)

- kss는 복잡한 뉴럴이나 통계기반이 아니라 단순한 규칙기반 휴리스틱 알고리즘 ("다" 앞에 무슨 글자 들어가거나 "요" 앞에 무슨 글자 들어가면 문장으로 분절하는 방식)으로 구현되어있습니다. 위의 경우는 "다" 앞에 "니"가 있었기 때문에 ("니다 + space")를 보고 분절한 것으로 보여집니다.

- 휴리스틱 구현의 한계이기도 한데, 진짜 자주 등장해서 이 프레이즈가 등장하면 대부분은 분절해도 괜찮겠다 싶은 부분이 아니면 분절하지 않는게 좋습니다. 즉 일반화해도 괜찮겠다 싶은 수준의 규칙이 아니라면 반영하기 어렵습니다. 오히려 부작용이 발생할 경우가 너무 많기 때문이죠. 대부분의 경우에는 "니다 + space"와 같은 프레이즈가 등장하면 문장의 끝맺음 부분일 확률이 굉장히 높기 때문에 저렇게 분절하는 규칙을 만든 것이죠.

- 가령 말씀하신 것 처럼 위의 케이스를 분절하는 로직을 kss에 추가하려면, 현재 정의된 "니다", "셨다", "했다", "온다" 등이 등장했다고 하더라도 바로 분절하지 않고 문장의 앞뒤 를 살핀 뒤 punctuation의 여부를 확인해서 문장을 refine 해줘야 하는데, 이와 같은 케이스는 일반화 해서 모든 경우에 적용 할 수 있는 수준이라고 보기에는 다소 어렵다고 판단됩니다.
  - 가령 `18,250,580주입니다 Mr. Kim은 다음과 같이 말했어요`  라는 문장이 있을 경우, `18,250,580주입니다 Mr.` 과 같이 분절하는 것은 타당하지 못한 분절입니다.
  - `18,250,580주입니다 음... 정말? 그게 맞아?`의 경우도 `18,250,580주입니다 음...`와 같이 분절하는 것은 타당하지 못합니다.
  - 마찬가지로 현재 kss는 `잘 지내니 응 나는 잘 지내 요즘 뭐해 그러게` 이런 문장도 분절이 안됩니다. `지내니` 부분에서 분절하는 것을 일반화 할 수 있는 수준으로 신뢰하기 어렵기 때문인데요. `너가 잘 지내니 보기 좋구나`와 같은 경우는 한 문장으로 처리해야합니다. 즉, 이렇게 세부적인 룰까지는 현재의 컨셉(휴리스틱)에서는 반영이 어렵습니다.
  - 저 정도 수준의 문장을 완벽하게 분리해내기를 원하신다면 휴리스틱 기반의 문장 분리기가 아닌 통계나 뉴럴넷 기반의 문장 분리기를 사용하는 것을 권장합니다.
- kss가 모든 경우의 수를 커버하는 100%의 성능은 보일 수 없다는 것에 대해 양해부탁드립니다. 😂

**Comment by joelkim** [comment]
네, 알겠습니다.
