### ISSUE TITLE
split_sentences() function 내 class 호출?

### ISSUE THREAD

**Issue by jaehyeongAN** [hyunwoongko/kss#10]
안녕하세요. 우선 제가 애용하는 kss 라이브러리를 잘 관리해주셔서 감사드립니다.😀
그 동안 kss==1.3.1버전을 잘 사용해오다가 2. 버전으로 올려볼까하여 테스트를 진행하고 있었는데 생각보다 1.3.x 버전과 속도 차이가 많이 나는 것을 확인하여 아직 1.3.1 버전을 유지 중입니다.

저는 text가 배치로 들어올 때마다 split_sentences()를 여러번 호출하는 일이 많다 보니 속도 저하가 더 크게 느껴지는데요😥
kss.py 코드를 살펴보니  split_sentences() 함수 [104번 라인](https://github.com/hyunwoongko/kss/blob/180e227040b5aa5f8fb4d6dadcfbb393d8261214/kss/kss.py#L104)
에서 2개의 class 호출이 이루어지고 있네요.(기존 1.3.1에서는 해당 function내 class 호출은 없었구요)
function 호출 시마다 class를 init하다보니 속도에 영향이 있지 않을까 생각됩니다. 어떻게 생각하시나요? (물론 기존 c++기반이 python기반으로 바뀌며 속도저하도 있으리라 생각됩니다)

**Comment by hyunwoongko** [comment]
안녕하세요. 우선 이렇게 메일 보내주셔서 감사합니다.속도 이슈는 기존 kss가 가진 수 많은 문제들을 해결하는 과정에서 발생하는 것이라고 생각드는데요. 현재의 kss는 기존 kss를 단순히 파이썬으로 포팅한 것 뿐만 아니라 기존 버전이 해결하지 못하던 따옴표 불일치시 분절하지 못하는 문제, 종결어미(EF)와 연결어미(EC)를 구분하지 못하는 문제, 다와 요에서 분절시 매우 제한적인 어간에만 작동되는 문제, 괄호 사이의 문장을 구별하지 못하는 문제 등 수 많은 문제점을 개선했구요. 그 과정에서 처리 시간이 발생하는 것으로 보입니다.알고리즘에 대해 공부해보셨다면 아시겠지만 대부분의 시간 이슈는 입력 데이터를 loop 시키는 부분에서 발생하구요. 단순히 객체가 생성되어 힙에 저장되는데 걸리는 시간은 매우 적을 것이기 때문에 (보통 마이크로 초 정도의 시간이 걸립니다) 그 부분에서 발생하는 시간은 거의 무시해도 될 것이라고 판단됩니다. (물론 아예 zero는 아니겠지만요)제 생각에는 우선 C기반이 아니라는 점, 다양한 문제를 매우 효과적으로 해결하고있는 백업 메커니즘에서의 루프 (2.XX 이후 도입), 조사/대명사 + 어간 + 다/요/죠 + 공백 지점에서 추가 분절 메커니즘에서의 루프 (2.XX 이후 도입)에서 추가적인 처리 시간이 드는 것으로 보이는데, 속도보다 무조건 성능이 우선이라는 판단을 가지고 개발에 임하고 있기 때문에, 이 부분에 있어서는 조금 더 고민해보도록 하겠습니다. 감사합니다.고현웅 올림.내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: jaehyeong <notifications@github.com> 날짜: 21/2/2  오후 7:31  (GMT+09:00) 받은 사람: hyunwoongko/kss <kss@noreply.github.com> 참조: Subscribed <subscribed@noreply.github.com> 제목: [hyunwoongko/kss] split_sentences() function 내 class 호출? (#10) 
안녕하세요. 우선 제가 애용하는 kss 라이브러리를 잘 관리해주셔서 감사드립니다.😀
그 동안 kss==1.3.1버전을 잘 사용해오다가 2. 버전으로 올려볼까하여 테스트를 진행하고 있었는데 생각보다 1.3.x 버전과 속도 차이가 많이 나는 것을 확인하여 아직 1.3.1 버전을 유지 중입니다.
저는 text가 배치로 들어올 때마다 split_sentences()를 여러번 호출하는 일이 많다 보니 속도 저하가 더 크게 느껴지는데요😥
kss.py 코드를 살펴보니  split_sentences() 함수 104번 라인
에서 2개의 class 호출이 이루어지고 있네요.(기존 1.3.1에서는 해당 function내 class 호출은 없었구요)
function 호출 시마다 class를 init하다보니 속도에 영향이 있지 않을까 생각됩니다. 어떻게 생각하시나요? (물론 기존 c++기반이 python기반으로 바뀌며 속도저하도 있으리라 생각됩니다)

**Comment by hyunwoongko** [comment]
안녕하세요. 우선 이렇게 메일 보내주셔서 감사합니다.


속도 이슈는 기존 kss가 가진 수 많은 문제들을 해결하는 과정에서 발생하는 것이라고 생각드는데요. 


현재의 kss는 기존 kss를 단순히 파이썬으로 포팅한 것 뿐만 아니라 기존 버전이 해결하지 못하던 따옴표 불일치시 분절하지 못하는 문제, 종결어미(EF)와 연결어미(EC)를 구분하지 못하는 문제, 다와 요에서 분절시 매우 제한적인 어간에만 작동되는 문제, 괄호 사이의 문장을 구별하지 못하는 문제 등 수 많은 문제점을 개선했구요. 그 과정에서 처리 시간이 발생하는 것으로 보입니다.


알고리즘에 대해 공부해보셨다면 아시겠지만 대부분의 시간 이슈는 입력 데이터를 loop 시키는 부분에서 발생하구요. 단순히 객체가 생성되어 힙에 저장되는데 걸리는 시간은 매우 적을 것이기 때문에 (보통 마이크로 초 정도의 시간이 걸립니다) 그 부분에서 발생하는 시간은 거의 무시해도 될 것이라고 판단됩니다. (물론 아예 zero는 아니겠지만요)


제 생각에는 우선 C기반이 아니라는 점, 다양한 문제를 매우 효과적으로 해결하고있는 백업 메커니즘에서의 루프 (2.XX 이후 도입), 조사/대명사 + 어간 + 다/요/죠 + 공백 지점에서 추가 분절 메커니즘에서의 루프 (2.XX 이후 도입)에서 추가적인 처리 시간이 드는 것으로 보이는데, 속도보다 무조건 성능이 우선이라는 판단을 가지고 개발에 임하고 있기 때문에, 이 부분에 있어서는 조금 더 고민해보도록 하겠습니다. 감사합니다.

**Comment by hyunwoongko** [comment]
말씀하신대로 속도가 중요하시다면 1.XX 버전을 사용하시는 것을 추천드리구요. 그러나 제가 작성한 테스트 케이스들에서 성능을 측정하면 반토막 납니다. 추가로 1.XX 버전은 어미 "죠" 에서 분절이 불가능합니다. 따라서 성능이 중요하시다면 2.XX 버전을 사용하시는 것을 추천드립니다.

**Comment by hyunwoongko** [comment]
말씀하신대로 속도가 중요하시다면 1.XX 버전을 사용하시면 더 빠르긴 할겁니다만 제가 작성한 테스트 케이스들(tests 폴더)에서 성능을 측정하면 거의 모든 케이스에서 문제가 발생하는 것을 보실 수 있습니다. test 케이스에 있는 test_from_uoneway()를 실행하시면 이 차이를 정량적으로 확인할 수 있는데요. `1.3.1`을 사용하시면 성능이 `2.4.0.1`의 반토막이 납니다.

```
- kss 1.3.1 accuracy : 
  0.39473684210526316

- kss 2.4.0.1 accuracy : 
  0.8921052631578947
```

성능 차이를 정성적으로 경험해보시려면 직접 각각의 테스트케이스들을 `1.3.1`에 넣어서 분절해보시길 권해드립니다. 한 가지 예시로 `1.3.1`과 최신버전인 `2.4.0.1`에 `"나는 대한민국의 이다정선수가 좋다 그녀는 좋은 모습을 보이다 최근 부진을 겪고 있다"`를 각각 입력해보시면 이전 버전에 어떤 문제들이 있고, 최근 버전이 이를 어떻게 해결했는지 알 수 있습니다.

```
- kss 1.3.1 split : 
  ['나는 대한민국의 이다', '정선수가 좋다 그녀는 좋은 모습을 보이다', '최근 부진을 겪고 있다']

- kss 2.4.0.1 split : 
  ['나는 대한민국의 이다정선수가 좋다', '그녀는 좋은 모습을 보이다 최근 부진을 겪고 있다']
```

추가로 1.XX 버전은 어미 "죠" 에서는 아예 분절이 불가능하기도 합니다. 따라서 속도 문제가 매우 크지 않으시다면 되도록 2.XX 버전을 사용하시는 것을 추천드립니다.

**Comment by jaehyeongAN** [comment]
네 아무래도 성능 향상이 많이 있다보니 최신버전을 사용하면서 적은 호출로 처리할 수 있도록 하는게 좋을 것 같네요! 친절한 답변 감사드립니다.😀
