### ISSUE TITLE
java 버전 개발 및 koalanlp 탑재.

### ISSUE THREAD

**Issue by hyunwoongko** [hyunwoongko/kss#11]
관련논의 :
https://github.com/koalanlp/python-support/issues/10

**Comment by nearbydelta** [comment]
KSS를 python KoalaNLP와 연동하고 나서, 코드를 좀 살펴보았습니다.
아래와 같이 Java 버전으로 만들면 어떨까 하고 생각해봤습니다.

1. kss/rule.py
   - 하나의 singleton instance라고 생각하면 될 것 같은데, 맞을까요?

2. kss/base.py
   - 여러 singleton instance들과 BackupManager class로 나뉠 것 같습니다.
   - QuoteException은 static method의 기능만 하는 것 같아서, kss.py가 하나의 class가 되면 그 하위 method로 들어가는게 어떨까 합니다.

3. kss/kss.py
   - 하나의 KSS class를 만들면 될 것 같은데, 
   - 다만 아래 부분을 class state를 사용해서 처리하면 좀 더 유지보수가 쉽지 않을까 하는 생각이 들었습니다.

https://github.com/hyunwoongko/kss/blob/3ac768324efb4de2ada183ea92b81f6876dee0ff/kss/kss.py#L176-L372 


그래서 다음과 같은 class 구조를 잡고 진행할까 합니다.
```text
com.github.hyunwoongko.kss
               |----- Rule.class
               |----- BackupManager.class
               |----- Constant.class
               |----- KSS.class
```

어떻게 생각하시는지요?
덧붙여, 어느 repo(새 repo인지 kss 하위인지 아니면 koalanlp인지)에 Java 소스를 업데이트할 것인지도 논의해야 할 것 같습니다.

**Comment by hyunwoongko** [comment]
네. 코드 구조는 말씀하신대로 만들면 큰 문제 없을 것 같구요.
java 코드는 여기에 구현하고, maven, gradle 등에 배포해서 코알라쪽에서 dependency로 가져가는건 어떠실까요?

**Comment by nearbydelta** [comment]
네 저는 좋습니다!

**Comment by hyunwoongko** [comment]
일단 그럼 이번주에 간단하게 자바버전 초안 제가 올려볼게요!
그거 보고 같이 이야기 나누시죠 ㅎㅎ

**Comment by hyunwoongko** [comment]
@nearbydelta 제가 바빠서 작업을 못했네요.. 
미팅 한번 하시면 좋을 것 같은데 시간 언제쯤 좋으세요?

**Comment by nearbydelta** [comment]
@hyunwoongko 저도 바빴는걸요.. ㅎㅎ 미팅은 화상 미팅을 말씀하시는 걸까요?

**Comment by hyunwoongko** [comment]
네 맞습니다 ㅎㅎ

**Comment by hyunwoongko** [comment]
java 버전 개발중... @sangdee

**Comment by hyunwoongko** [comment]
개발완료. 배포만 남음.

**Comment by nearbydelta** [comment]
하나도 도움을 못 드렸네요 ㅠㅠ
제가 지금 9월 초에 낼 논문 작성때문에 바빠서.. 죄송합니다 ㅠ

**Comment by hyunwoongko** [comment]
@nearbydelta https://github.com/sangdee/kss-java 
java버전 배포까지 완료되었습니다. 시간나실때 천천히 탑재해주시면 좋을것 같습니다.
그리고 파이썬 버전은 3.xx로 업데이트 되었으니 반영해주시면 좋을것 같습니다.

(+ arugument 이름들이 좀 바뀌었는데 **kwargs로 입력되게끔 하는게 좋을것 같아요~ 다음에 또 변경될수도 있으니까요)

**Comment by hyunwoongko** [comment]
@nearbydelta 진행이 전혀 안되고 있네요. 혹시 진행하실 의사 있으실까요? 없으시면 이슈 클로징 하려고합니다.

**Comment by hyunwoongko** [comment]
이슈 클로징합니다.
