### ISSUE TITLE
무한 재귀 호출 현상 

### ISSUE THREAD

**Issue by jaehyeongAN** [hyunwoongko/kss#13]
https://github.com/hyunwoongko/kss/issues/6
위 이슈와 같은 문제인지는 정확히 모르겠으나, 테스트해보는 도중 같은 이슈가 발생하여 코멘트납깁니다!

website를 크롤링 후 텍스트만 추출하여 kss 문장분리를 시도하고 있었는데,  
[정상적이지 않은 script 텍스트](https://github.com/hyunwoongko/kss/files/5941185/bug_text.txt)가 입력으로 들어가며 함수 내에서 못빠져나오는 현상을 경험했습니다.

제가 대략 코드를 살펴본 바로는 
kss.py 내 [split_sentences()](https://github.com/hyunwoongko/kss/blob/main/kss/kss.py#L96) 함수와 [realign_by_quote()](https://github.com/hyunwoongko/kss/blob/main/kss/kss.py#L46)함수가 재귀함수로서 서로를 call하는 상황에서 

split_sentence() 함수의 [아래 코드 부분](https://github.com/hyunwoongko/kss/blob/main/kss/kss.py#L275)의 if 조건에 계속 빠지면서 realign_by_quote()함수가 다시 split_sentences()를 call하는  무한 function call 상황이 발생하는 것 같습니다.
```python
if len(single_quote_stack) != 0:
    results = realign_by_quote(text, last_single_quote_pos, "'")

if len(double_quote_stack) != 0:
    results = realign_by_quote(text, last_double_quote_pos, "\"")

if len(bracket_stack) != 0:
    results = realign_by_quote(text, last_bracket_pos, " ")
```

_Originally posted by @jaehyeongAN in https://github.com/hyunwoongko/kss/issues/6#issuecomment-774848082_

**Comment by hyunwoongko** [comment]
제보 감사합니다. 해당 메커니즘은 따옴표와 괄호 등의 개수가 맞지 않을 때, 이를 맞추기 위해 수행됩니다.

제시해주신 텍스트는 프로그램 코드로 보이는데, 프로그램 코드 특성상 괄호와 따옴표가 매우 많이 등장하기 때문에 이 function의 call이 매우 많아진 것으로 보입니다. 말씀하신대로 이 재귀함수를 몇번 호출할지에 대한 제한을 두는 것도 좋아보이네요. 검토해보고 적용해보도록 하겠습니다. 감사합니다.

**Comment by hyunwoongko** [comment]
```
>>> from kss import split_sentences
>>> text = "...very long text..."

>>> split_sentences(text, max_recover_step=5)
>>> # you can adjust recovery (recursive) depth using `max_recover_step` (default is 5)

>>> split_sentences(text, max_recover_length=20000)
>>> # you can turn it off when you inputted very long text using `max_recover_length` (default is 20000)
```

해당 문제를 해결했구요. 파라미터를 이용해 더 세분화된 조절이 가능하도록 업데이트 했습니다.
- `max_recover_step` 를 통해 최대 재귀호출 Depth를 결정할 수 있습니다. (default는 5입니다.)
- `max_recover_length`를 통해 일정 길이 이상의 텍스트에 대해 이 기능을 끌 수 있습니다 (default는 20,000입니다.)

**Comment by jaehyeongAN** [comment]
네 친절한설명 감사드리고 이슈 빠르게 처리해주셔서 감사합니다!
