### ISSUE TITLE
KSS 설치이슈

### ISSUE THREAD

**Issue by reasonmii** [hyunwoongko/kss#17]
안녕하세요, KSS를 사용하고 싶은데 설치가 되지 않아 문의드립니다.

아나콘다 쥬피터 노트북에서 파일을 실행하고 싶은데 kss 가 다운이 되지 않습니다. 아나콘다 prompt 에서 'pip install', 'conda install kss', 'conda install -c conda-forge kss' 를 모두 시도해도 계속 PackagesNotFoundError 에러가 발생합니다. 어떤 명령어로 설치가 가능한가요??

**Comment by hyunwoongko** [comment]
pip install kss로 설치하시면 됩니다.
콘다에 올려놓지 않아서 안될거에요.

**Comment by hyunwoongko** [comment]
특별히 더 논의할 사항 없으시면 이슈를 닫도록 하겠습니다.
논의할 사항이 생기면 다시 열어주세요~
