### ISSUE TITLE
오류 보고

### ISSUE THREAD

**Issue by joelkim** [hyunwoongko/kss#3]
```
from kss import split_sentences
para = 'TV산업은 1926년 흑백 TV 개발, 1954년 RCA사가 Color TV(21") 양산/판매를 시작한 이래로 트리니트론 브라운관(1967년), 완전평면 브라운관(1996년) 개발 등 기술적인 발전을 거듭해 왔으나, 주요 국가 보급률이 90%를 넘어서면서 브라운관 TV사업의 성장은 정체되었습니다. 그러나 Flat Panel TV(LCD, PDP) 출시, 디지털 방송 확산(영/미 1998년~ )을 통해 TV 시장은 성장 모멘텀을 되찾았으며, FPTV는 화질, 디자인 등 제품 성능 향상과 지속적인 Set가격 하락을 통해 성장을 지속하며 기존 CRT 시장을 빠르게 대체하였습니다. 또한 2010년 입체감을 느낄 수 있는 3D TV가 출시되었고, 2011년부터 2012년에 걸쳐 인터넷 동영상 서비스 업체들의 부상과 스마트기기에 대한 사용자들의 관심 확대로 스마트 TV 시장이 태동하였습니다. 2013년에는 화질 및 해상도가 혁신적으로 높아진 UHD TV, 2014년에는 새로운 Form Factor인 Curved TV가 출시되었으며 2015년에는 퀀텀닷TV가 상용화되는 등 TV 시장은 끊임없이 진화하였습니다.전체 TV 수요는 2017년 기준 2억 1,510만대 수준으로 LCD TV 수요가 2억 1천만대로 99% 이상의 시장 점유를 이어 나갔으며, OLED 수요는 159만대로 성장하였으나 비중은 0.7%로 영향이 미미하였습니다. 2018년도 전체 TV 수요는 2억 2,100만대 이상을 기록하며 전년 대비 2.9% 성장하였습니다. 최근 TV시장은 고해상도 대형화면에 대한 Needs가 지속적으로 증가하여, UHD TV는 전년비 26% 증가한 99.6백만대로 시장 비중 45% 수준이 될 전망이며, 60"이상 대형시장은 약 19.7백만대를 초과하여 전년비 35% 성장, 75"이상 초대형 시장도 당사의 판매 드라이브로 전년비 76% 이상 성장이 전망되고 있습니다.'
split_sentences(para)
```

결과: 문장 분리가 되지 않음

```
['TV산업은 1926년 흑백 TV 개발, 1954년 RCA사가 Color TV(21") 양산/판매를 시작한 이래로 트리니트론 브라운관(1967년), 완전평면 브라운관(1996년) 개발 등 기술적인 발전을 거듭해 왔으나, 주요 국가 보급률이 90%를 넘어서면서 브라운관 TV사업의 성장은 정체되었습니다. 그러나 Flat Panel TV(LCD, PDP) 출시, 디지털 방송 확산(영/미 1998년~ )을 통해 TV 시장은 성장 모멘텀을 되찾았으며, FPTV는 화질, 디자인 등 제품 성능 향상과 지속적인 Set가격 하락을 통해 성장을 지속하며 기존 CRT 시장을 빠르게 대체하였습니다. 또한 2010년 입체감을 느낄 수 있는 3D TV가 출시되었고, 2011년부터 2012년에 걸쳐 인터넷 동영상 서비스 업체들의 부상과 스마트기기에 대한 사용자들의 관심 확대로 스마트 TV 시장이 태동하였습니다. 2013년에는 화질 및 해상도가 혁신적으로 높아진 UHD TV, 2014년에는 새로운 Form Factor인 Curved TV가 출시되었으며 2015년에는 퀀텀닷TV가 상용화되는 등 TV 시장은 끊임없이 진화하였습니다.전체 TV 수요는 2017년 기준 2억 1,510만대 수준으로 LCD TV 수요가 2억 1천만대로 99% 이상의 시장 점유를 이어 나갔으며, OLED 수요는 159만대로 성장하였으나 비중은 0.7%로 영향이 미미하였습니다. 2018년도 전체 TV 수요는 2억 2,100만대 이상을 기록하며 전년 대비 2.9% 성장하였습니다. 최근 TV시장은 고해상도 대형화면에 대한 Needs가 지속적으로 증가하여, UHD TV는 전년비 26% 증가한 99.6백만대로 시장 비중 45% 수준이 될 전망이며, 60"이상 대형시장은 약 19.7백만대를 초과하여 전년비 35% 성장, 75"이상 초대형 시장도 당사의 판매 드라이브로 전년비 76% 이상 성장이 전망되고 있습니다.']
```

**Comment by hyunwoongko** [comment]
- 안녕하세요. 좋은 피드백 항상 감사드립니다.

- ") 양산/판매를 시작한 이래로 트리니트론 브라운관(1967년), 완전평면 브라운관(1996년) 개발 등 기술적인 발전을 거듭해 왔으나, 주요 국가 보급률이 90%를 넘어서면서 브라운관 TV사업의 성장 은 정체되었습니다. 그러나 Flat Panel TV(LCD, PDP) 출시, 디지털 방송 확산(영/미 1998년~ )을 통해 TV 시장은 성장 모멘텀을 되찾았으며, FPTV는 화질, 디자인 등 제품 성능 향상과 지속적인 Set가격 하락을 통해 성장을 지속하며 기존 CRT 시장을 빠르게 대체하였습니다. 또한 2010년 입체감을 느낄 수 있는 3D TV가 출시되었고, 2011년부터 2012년에 걸쳐 인터넷 동영상 서비스 업체들의 부상과 스마트기기에 대한 사용자들의 관심 확대로 스마트 TV 시장이 태동하였습니다. 2013년에는 화질 및 해상도가 혁신적으로 높아진 UHD TV, 2014년에는 새로운 Form Factor인 Curved TV가 출시되었으며 2015년에는 퀀텀닷TV가 상용화되는 등 TV 시장은 끊임없이 진화하였습니다.전체 TV 수요는 2017년 기준 2억 1,510만대 수준으로 LCD TV 수요가 2억 1천만대로 99% 이상의 시장 점유를 이어 나갔으며, OLED 수요는 159만대로 성장하였으나 비중은 0.7%로 영향이 미미하였습니다. 2018년도 전체 TV 수요는 2억 2,100만대 이상을 기록하며 전년 대비 2.9% 성장하였습니다. 최근 TV시장은 고해상도 대형화면에 대한 Needs가 지속적으로 증가하여, UHD TV는 전년비 26% 증가한 99.6백만대로 시장 비중 45% 수준이 될 전망이며, 60"

- 위 부분 때문에 그런 것인데요. 일반적으로 " "와 같은 따옴표들은 화면의 인치 보다는 대화나 사람의 말 등을 전할 때 쓰는 경우가 훨씬 많습니다. 또한 사람의 말 사이에서는 문장으로 분절을 하지 않는 것이 맞습니다. 예를 들어보면 `그가 "철수가 다시 온다고 했어요. 진짜로" 라고 말하자마자 철수가 도착했다.` 라는 문장이 있다고 해봅시다. 이 때, " " 따옴표 사이에서 문장을 분절하면`그가 "철수가 다시 온다고 했어요.` `진짜로" 라고 말하자마자 철수가 도착했다.` 와 같이 문장이 분절되기 때문에 현재 모듈에는 띄어쓰기 사이의 문장은 분절하지 않는다라는 원칙이 포함되어있습니다.

- 위의 경우 " "가 대화가 아닌 인치를 표현하기 위해 사용되었는데, " " 사이에 들어간 텍스트가 대화인지, " "가 인치 등으로 사용되었는지 구분하는 것은 꽤 어려운 문제입니다. (그러나 일반적으로는 대화나 사람의 말을 인용하는 경우에 사용되는 것이 압도적이죠.)

- 따옴표 관련 알고리즘은 제가 고안한 것이 아니라 kss의 원작자인 박상길님(likejazz)의 구현에서 부터 존재하던 부분이구요. 이전에도 말했던 것 처럼 휴리스틱 기반의 문장분석기가 완벽할 수 없다는 점은 양해를 드립니다. 추가로 kss의 동작 방식에 대해서는 다음 [문서](http://docs.likejazz.com/kss/)에서 확인 가능합니다.

- 그리고 이 부분은 저도 고민을 하고 있는 부분인데, 애초에 대량의 데이터로 뉴럴넷에 학습을 시키면 더 나을 수도 있겠다라는 생각은 듭니다만, 이 패키지에서 torch나 tensorflow 디펜던시 껴서 개발하는 것은 아닌 것 같고 (kss는 애초에 컨셉이 휴리스틱 문장분리기이니...) 추후에 다른 문장분리기를 만들게 된다면 말씀드리도록 하겠습니다.

- kss의 성능 때문에 고민이시라면 kss 말고도 형태소분석기에 문장분리 모듈이 탑재된 것들이 있습니다. 또한 그들에 대한 성능을 비교한 자료도 존재하는데요. [여기](http://semantics.kr/%ED%95%9C%EA%B5%AD%EC%96%B4-%ED%98%95%ED%83%9C%EC%86%8C-%EB%B6%84%EC%84%9D%EA%B8%B0-%EB%B3%84-%EB%AC%B8%EC%9E%A5-%EB%B6%84%EB%A6%AC-%EC%84%B1%EB%8A%A5%EB%B9%84%EA%B5%90/)에서 확인 가능합니다. 그런데 몇몇 분석기들은 당연히 분절되어야 할 곳에서 분절되지 않는 경우도 꽤 많습니다. 반대로 kss 처럼 휴리스틱 분석의 한계로 문장 분절이 안되는 경우를 잘 잡아내줄 때도 있죠. 사용해보시고, 더 잘 동작한다고 생각하시는 도구를 사용하시면 좋을 것 같습니다. 감사합니다.

**Comment by hyunwoongko** [comment]
이슈는 계속 열어놓겠습니다. 이 부분을 반영해서 버전 업데이트를 하고 닫도록 하겠습니다.

**Comment by joelkim** [comment]
답변 감사합니다.

**Comment by hyunwoongko** [comment]
- https://github.com/hyunwoongko/kss/blob/379a8db4585ec7e6c9e345ee90c8aa9622e5c119/kss/kss.py#L297
- 해당 이슈를 반영하여 다양한 어퍼스트로피와 프라임에 대한 예외처리를 추가했습니다. (version 2.1)
-`pip install kss --upgrade`를 통해 업그레이드하시면 적용됩니다. 감사합니다.
