### ISSUE TITLE
Initializing Pynori... 한번후 재사용가능한지요?

### ISSUE THREAD

**Issue by hunkim** [hyunwoongko/kss#31]
한번 분석하는데 시간이 좀 오래 걸리는것 같은데 혹시 `Pynori` 초기화를 한번해둔다음 재 사용가능한 방법이 있나요? 이 초기화에서 시간이 많이 걸리는것 같습니다.

**Comment by hyunwoongko** [comment]
안녕하세요. 일단 지금 구현은 맨 처음에 한번만 로드하도록 되어있습니다.

**Comment by hyunwoongko** [comment]
Pynori 대신 Mecab 백엔드를 사용하시면 시간을 아낄 수 있으시고, Mecab 설치가 여의치 않으시면 none 백엔드를 이용하시면 시간을 절약할 수 있습니다. 다만 none 백엔드를 이용할시에는 분석성능이 감소됩니다.
