### ISSUE TITLE
문장분리기 실행시 여러번 호출되면서 오류가 발생합니다.

### ISSUE THREAD

**Issue by CivilPro9** [hyunwoongko/kss#37]
![image](https://user-images.githubusercontent.com/87063075/152351226-7bcd410b-97f2-4152-a20d-82658fe012d1.png)

안녕하세요. 텍스트 마이닝 공부를 하고 있는 학생입니다.

다름이 아니라, 문장 분리기 사용시 수없이 많이 호출되며 런타임 오류가 발생하는데, 이유가 무엇인지 알 수 있을까요?

이 오류는 vs code에서는 발생하며 jupyter notebook에서 실행하면 잘됩니다.

제가 아직 코딩 초보자라 검색해봤지만 이에 대한 해결법을 찾지 못해서 여쭤봅니다.

감사합니다.

**Comment by hyunwoongko** [comment]
멀티프로세싱 때문인 것 같아요.

```python
if __name__ == '__main__':
    kss 실행 코드
```

이렇게 해보시겠어요?

**Comment by hyunwoongko** [comment]
https://github.com/hyunwoongko/kss/issues/36#issuecomment-1040813757

이 이슈와도 관련이 있어보이네요.

**Comment by hyunwoongko** [comment]
이 문제는 멀티프로세싱 관련 환경 문제인 것 같구요.
일단 kss측의 문제는 아닌 것 같아서 이슈는 클로징하겠습니다. 

문제 생기시면 다시 열어주세요~
