### ISSUE TITLE
안녕하세요. flutter 용으로 제작 하였습니다. 

### ISSUE THREAD

**Issue by khjde1207** [hyunwoongko/kss#43]
안녕하세요. 
한글 문장 분리 검색하다가 kss 라리브러리를 찾게 되었습니다. 
제가 사용하는 flutter 로는 제작되어 있지 않아. kss_java 코드를 수정하여 제작 하였습니다. 

https://github.com/khjde1207/kss_dart

좋은 라이브러리를 제공해 주셔서 감사합니다.

**Comment by hyunwoongko** [comment]
기여 감사합니다. 리드미에 추가하겠습니다.
