### ISSUE TITLE
문장 분리 오류

### ISSUE THREAD

**Issue by MrBananaHuman** [hyunwoongko/kss#5]
안녕하세요!
우선 자연어처리에 필수로 필요한 라이브러리를 공유해주셔서 진심으로 감사드립니다.
해당 라이브러리를 사용 중, 문장 분리가 이상하게 되는 경우를 발견해서 이슈로 남깁니다.

kss==2.2.0.2
"개그맨 김병만 씨가 아르바이트를 하다 목숨을 잃을 뻔한 사연을 TV조선 '별별톡쇼'에서 전했다."
->['개그맨 김병만 씨가 아르바이트를 하다', "목숨을 잃을 뻔한 사연을 TV조선 '별별톡쇼'에서 전했다."]

감사합니다 :-)

**Comment by MrBananaHuman** [comment]
추가로, 아래의 문장도 분리가 이루어지는게 맞다고 생각합니다.. :-)

"왼쪽 위 사진부터 시계방향으로 서울 종로구 인사동, 광주 동구 동명동 거리, 서울 망우본동 우림시장, 대구시 중구 남산동 상가에 붙은 ‘착한 임대인 운동’관련 감사문구.(사진=저작권자(c) 연합뉴스, 무단 전재-재배포 금지)"

**Comment by hyunwoongko** [comment]
안녕하세요. 피드백 남겨주셔 감사합니다 😁

우선 윗쪽 문장은 버그가 맞구요. 아래쪽 문장은 어떻게 분절되길 원하시는 건가요?

**Comment by MrBananaHuman** [comment]
안녕하세요! :-)

제 생각엔.. 해당 문장이 다음과 같이 두 문장으로 분리되야할 것 같아서요 :-)

[1]: 왼쪽 위 사진부터 시계방향으로 서울 종로구 인사동, 광주 동구 동명동 거리, 서울 망우본동 우림시장, 대구시 중구 남산동 상가에 붙은 ‘착한 임대인 운동’관련 감사문구.
[2]: (사진=저작권자(c) 연합뉴스, 무단 전재-재배포 금지)

예시 문장을
"왼쪽 위 사진부터 시계방향으로 서울 종로구 인사동, 광주 동구 동명동 거리, 서울 망우본동 우림시장, 대구시 중구 남산동 상가에 붙은 ‘착한 임대인 운동’관련 감사문구이다.(사진=저작권자(c) 연합뉴스, 무단 전재-재배포 금지)"

이렇게 변형하게 되면, 

[1]: 왼쪽 위 사진부터 시계방향으로 서울 종로구 인사동, 광주 동구 동명동 거리, 서울 망우본동 우림시장, 대구시 중구 남산동 상가에 붙은 ‘착한 임대인 운동’관련 감사문구이다.
[2]: (사진=저작권자(c) 연합뉴스, 무단 전재-재배포 금지)

두개로 분리가 이루어집니다.. :-)

**Comment by hyunwoongko** [comment]
- 글쎄요. 말씀하신대로 분절할 수도 있는데, 이 부분은 뭔가 명확한 분절점이라고 보기는 어려운 것 같아요. 무엇보다 kss는 룰 베이스로 돌아가는데 저 부분 룰을 어떻게 줘야 할지 감이 안오네요.. ".(" (마침표 + 괄호)로 주면 좋으려나... 근데 그렇게 하면 `‘착한 임대인 운동’관련 감사문구 (사진=저작권자(c) 연합뉴스, 무단 전재-재배포 금지)`와 같이 마침표가 빠지는 경우에는 다시 분절이 안되겠죠. 

- 분절 하고 말고의 개념적인 문제보다도 구현의 입장에서 이게 확률같은 개념을 전혀 안쓰고 있기 때문에 저렇게 어떨때는 자르고, 어떨때는 안자르고 이런게 안됩니다. 룰 베이스의 한계인거죠. 그래서 이런 저런 케이스를 전부 고려하는건 좀 어려워요. 그렇다고 해서 괄호가 나왔다고 무조건 다 자르게 하면 안되겠죠. 가령 `"내가 전에 (돈에 대해서) 말했던 것 기억나?"`라는 문장이 입력되면, 이걸 `"내가 전에"` `"(돈에 대해서)"` `"말했던 것 기억나?"`같이 잘라질테니까요. 

- 우선 가장 먼저 올려주신 `개그맨 김병만 씨가 아르바이트를 하다 목숨을 잃을 뻔한 사연을 TV조선 '별별톡쇼'에서 전했다.`는 확실히 고쳐야 되는 버그라고 생각이 듭니다만, 아래쪽 문장은 고려를 해봐야할 것 같아요. 저 부분이 과연 분절해야하는 부분인지 아닌지에 대해서 + 만약 분절 할거라면 룰을 어떻게 줘야할지에 대해서요.

**Comment by hyunwoongko** [comment]
저도 만들면서 생각이 든 부분인데, 부분적으로 확률이나 머신러닝 기법을 도입해야 할 것 같다는 생각이 들더라구요. 그렇다고 무거운 딥러닝은 아닌 것 같고, 기본적으로 rule 베이스로 가되, 부분부분 애매한 부분에서는 간단한 머신러닝 알고리즘 (naive bayes나 svm 같은..)을 이용해보는건 어떨까 생각도 들고... 모르겠네요 ㅋㅋㅠ 베이스가 규칙 기반인 이상 완벽을 추구할 순 없는 것 같아요..

**Comment by MrBananaHuman** [comment]
피드백 감사드립니다!! :-)
말씀해주신대로 명확하지 않고(?) 구현 관점에서도 무척 어려운 문제네요.. :-)....

첫 번째 예제의 경우에는 분절이 안되는 것이 맞을 것 같은데,
그러면 두 번째 예제 케이스와 구분이 안되기 시작할 것 같구요.. :-)..
고생이 많으십니다......😂😂😂

**Comment by MrBananaHuman** [comment]
히히.. deep-kss 가 곧 탄생하겠네요... 🤗🤗

**Comment by hyunwoongko** [comment]
우선 첫번째 문제 (김병만 ...) 해결되면 다시 말씀드릴게요! 금방 고칠 수 있을 것 같아요.

**Comment by MrBananaHuman** [comment]
정말 감사드립니다! :D

**Comment by hyunwoongko** [comment]
이 문제 상당히 복잡하네요... 음 

#### 갔다
- (분절 ?) s = "그는 전쟁터에 갔다"
- (분절 O) s = "그는전쟁터에 갔다 돌잔치가 시작하자 아들이 떠올랐다"
- (분절 X) s = "그는 전쟁터에 갔다 돌아왔다"
<br>

#### 었다
- (분절 ?) s = "그는 기억력이 나빠서 그 사실을 잊었다"
- (분절 O) s = "그는 기억력이 나빠서 그 사실을 잊었다 기나긴 밤이 지나고 그는 드디어 기억났다"
- (분절 X) s = "그는 기억력이 나빠서 그 사실을 잊었다 기억했다를 반복했다"

<br>

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅠ 아..

**Comment by hyunwoongko** [comment]
원래 "하다가"로 써야하는데 ("하다가"는 rule에 안자르는 것으로 되어있어요) 이게 "하다"로 축약되어버리는 케이스인데, 축약한지 원래 이게 종결어미인지 어떻게 분별할까요....

**Comment by MrBananaHuman** [comment]
이정도 되면 형태소 분석 없이는 너무 어려울 것 같은데요...
저도 혹시 아이디어가 생각나면 코멘트 달게요... 😢😢

**Comment by hyunwoongko** [comment]
- OKT : Verb (동사)
[('개그맨', 'Noun'), ('김병만', 'Noun'), ('씨', 'Noun'), ('가', 'Josa'), ('아르바이트', 'Noun'), ('를', 'Josa'), ('하다', 'Verb'), ('목숨', 'Noun'), ('을', 'Josa'), ('잃을', 'Verb'), ('뻔한', 'Adjective'), ('사연', 'Noun'), ('을', 'Josa'), ('TV', 'Alpha'), ('조선', 'Noun'), ("'", 'Punctuation'), ('별별', 'Modifier'), ('톡쇼', 'Noun'), ("'", 'Punctuation'), ('에서', 'Josa'), ('전', 'Noun'), ('했다', 'Verb'), ('.', 'Punctuation')]

- Kkma : NNP (일반명사... ㅋㅋㅋㅋ)
[('개그맨', 'NNG'), ('김', 'NNG'), ('병', 'NNG'), ('만', 'JX'), ('씨', 'NNG'), ('가', 'JKS'), ('아르바이트', 'NNG'), (' 를', 'JKO'), ('하다', 'NNP'), ('목숨', 'NNG'), ('을', 'JKO'), ('잃', 'VV'), ('을', 'ETD'), ('뻔', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('사연', 'NNG'), ('을', 'JKO'), ('TV', 'OL'), ('조선', 'NNG'), ("'", 'SS'), ('별', 'NNG'), ('별', 'NNG'), ('톡', 'MAG'), ('쇼', 'NNG'), ("'", 'SS'), ('에서', 'JKM'), ('전하', 'VV'), ('었', 'EPT'), ('다', 'EFN'), ('.', 'SF')]

- Hannanum : P + E (동사 + 어미)
- [('개그맨', 'N'), ('김병', 'N'), ('만', 'J'), ('쓰', 'P'), ('어', 'E'), ('가', 'P'), ('아', 'E'), ('아르바이트', 'N'), ('를', 'J'), ('하', 'P'), ('어다', 'E'), ('목숨', 'N'), ('을', 'J'), ('잃', 'P'), ('을', 'E'), ('뻔하', 'P'), ('ㄴ', 'E'), ('사연', 'N'), ('을', 'J'), ('TV', 'F'), ('조', 'N'), ('선', 'J'), ("'별별톡쇼'", 'N'), ('에서', 'J'), ('전하', 'P'), ('었다', 'E'), ('.', 'S')]


음.. 형태소 분석기로도 어려워보이고 Dependency Parsing 모델이 필요할 것 같아요..

**Comment by hyunwoongko** [comment]
우선 완벽하게 모든 케이스를 잡는건 불가능해보이고, "다"의 경우는 동사원형은 전부 빼볼게요. "하다", "먹다", "자다" 등은 실제로 문어체에서 그것도 매우 특별한 케이스에서만 사용되고 거의 사용되지 않으니까요.

**Comment by hyunwoongko** [comment]
와 mecab이 짱이네요 역시... 연결어미(EC)로 잡아내네요.

[('개그맨', 'NNG'), ('김병만', 'NNP'), ('씨', 'NNB'), ('가', 'JKS'), ('아르바이트', 'NNG'), ('를', 'JKO'), ('하', 'VV'), ('다', 'EC'), ('목숨', 'NNG'), ('
을', 'JKO'), ('잃', 'VV'), ('을', 'ETM'), ('뻔', 'NNB'), ('한', 'XSA+ETM'), ('사연', 'NNG'), ('을', 'JKO'), ('TV', 'SL'), ('조선', 'NNP'), ("'", 'SY'), ('
별별', 'MM'), ('톡', 'NNG'), ('쇼', 'NNG'), ("'", 'SY'), ('에서', 'JKB'), ('전했', 'VV+EP'), ('다', 'EF'), ('.', 'SF')]

**Comment by hyunwoongko** [comment]
우선 완벽하게 해결하는 건 어려워보이고, 임시방편으로 동사 원형 + "다"는 전부 제거해놓을게요. "먹다", "하다", "자다" 같은 형태로는 아주 제한적인 상황에서만 사용되니까요.

**Comment by hyunwoongko** [comment]
이전보다 EC ↔ EF 문제가 많이 개선되었을 거에요!
`pip install kss --upgrade`로 업데이트 하시고 사용해보시길 바랍니다.
문제 있으시면 다시 이슈 남겨주세요~
