### ISSUE TITLE
종결어미(~함, ~임)이 앞에 붙는 단어에 따라 종결 어미로 인식 안되는 이슈

### ISSUE THREAD

**Issue by Eolee1** [hyunwoongko/kss#50]
테스트 해보니 ~함, ~임이 앞에 붙는 단어에 따라 문장을 분리시켜주지 못하는 이슈가 있습니다.

~함 : 형성함, 지원함 등
   ex) 명확히 기대하는 바를 제시하고 이를 달성하기 위한 제반 여건을 지원함 편견 없이 다른 사람의 다양성에 집중하는
          => 분리안됨
~임 : ~편임

혹시, ~함, ~임 앞에 특정 요건이 있어야 ~함, ~임을 종결어미로 인식하여 앞뒤 문장을 분리시켜주는지 궁금합니다.

**Comment by hyunwoongko** [comment]
안녕하세요. 말씀해주신 부분은 국어 문법상 종결어미가 아닌 명사형 전성어미에 해당하구요.
명사형 전성어미는 잘못 자르면 크게 낭패를 볼 수 있기 때문에 (예를 들어 "그러함에 있어서", "반짝임을 보았다" 등..) 가급적 확실한 경우에만 분리하도록 개발하였습니다. 감사합니다.

**Comment by hyunwoongko** [comment]
@Eolee1 안녕하세요. 

말씀해주신 부분은 국어 문법상 종결어미가 아닌 명사형 전성어미에 해당합니다. 
말씀하신 예제 중에서 '형성하다'의 종결어미 '하다'를 명사 활용형인 '함'으로 변경함으로써 명사형으로 쓸 수 있는거죠. 
현재 kss는 https://github.com/hyunwoongko/kss/blob/main/kss/kss.py#L419 에서와 같이 명사형 전성어미도 구분할수 있도록 구현하였습니다. 
다만 이러한 명사형 전성어미들은 잘못 자르면 크게 낭패를 볼 수 있기 때문에 가급적 확실한 경우에만 분리하도록 개발하였습니다. 

감사합니다.

**Comment by hyunwoongko** [comment]
3.7.0에서 일부 개선되었습니다.
