### ISSUE TITLE
줄바꿈 문장 분리 오류 문제

### ISSUE THREAD

**Issue by silverya** [hyunwoongko/kss#57]
text = '''1. 옆 자리의 직원이 ~~ 라고 말했다.
  1-1. 아직도 3시밖에 안 됐네.
  1-2. 빨리 집에 가고싶다. '''

`
s = split_sentences(text)
`

output : ['1. 옆 자리의 직원이 ~~ 라고 말했다.']

진행했을때, 문장 분리 결과로 첫번째 문장밖에 출력이 안됩니다.

kss==3.7.3 버전

**Comment by hyunwoongko** [comment]
4.0.0에서 해결되었습니다.
