### ISSUE TITLE
30000자 이상 sentence split 시 과도하게 느려지거나 프리징 현상

### ISSUE THREAD

**Issue by seongwook-ham** [hyunwoongko/kss#6]
환경 : ubuntu 18.04 python 3.8 kss python version 2.2.0.2 
30000이상의 text를 split sentence 할 때 text에 따라 100배 이상 느리거나 혹은 끝나지 않는 문제가 있습니다.
정상적으로 처리되는 것도 있고요.
6시간이 지나도 끝나지 않아요 30000자 처리하는데.
혹시 time complexity 이슈인지 혹은 끝나지 않는 loop가 있는지 궁금합니다.
같은것을 1.3.1버전으로 처리해보면 잘 됩니다.
텍스트는 저작권 이슈로 올릴수가 없습니다.

**Comment by hyunwoongko** [comment]
글쎄요. 타임컴플렉시티 부분에서의 문제는 아니구요.
뭔가 버그가 있는 것 같은데, 원본 텍스트를 올려주시지 못하면 재현이 안되어서 직접 해결은 어려워 보입니다.

**Comment by jaehyeongAN** [comment]
위 이슈와 같은 문제인지는 정확히 모르겠으나, 테스트해보는 도중 같은 이슈가 발생하여 코멘트납깁니다!

website를 크롤링 후 텍스트만 추출하여 kss 문장분리를 시도하고 있었는데,  
[bug_text.txt](https://github.com/hyunwoongko/kss/files/5941185/bug_text.txt)
위와 같은 script 텍스트가 입력으로 들어가며 함수 내에서 못빠져나오는 현상을 경험했습니다.

제가 대략 코드를 살펴본 바로는 
kss.py 내 [split_sentences()](https://github.com/hyunwoongko/kss/blob/main/kss/kss.py#L96) 함수와 [realign_by_quote()](https://github.com/hyunwoongko/kss/blob/main/kss/kss.py#L46)함수가 재귀함수로서 서로를 call하는 상황에서 

split_sentence() 함수의 아래 코드 부분의 if 조건에 계속 빠지면서 realign_by_quote()함수가 다시 split_sentences()를 call하는  무한 function call 상황이 발생하는 것 같습니다.
`
if len(single_quote_stack) != 0:
    results = realign_by_quote(text, last_single_quote_pos, "'")

if len(double_quote_stack) != 0:
    results = realign_by_quote(text, last_double_quote_pos, "\"")

if len(bracket_stack) != 0:
    results = realign_by_quote(text, last_bracket_pos, " ")
`
